from __future__ import annotations

from pathlib import Path


def generate_cmake(
    output_dir: str,
    known_apis: dict[str, dict],
    used_headers: set[str],
) -> None:
    """Generate a top-level CMakeLists.txt for the mock SDK tree."""
    dest = Path(output_dir)
    dest.mkdir(parents=True, exist_ok=True)

    # Collect all source files that were actually generated
    source_files: list[str] = []
    for hdr_path_str in sorted(used_headers):
        entry = known_apis.get(hdr_path_str)
        if not entry:
            continue
        functions = entry.get("functions", {})
        if not functions or all(
            f.get("kind") == "inline" for f in functions.values()
        ):
            continue
        src = f"source/{Path(hdr_path_str).with_suffix('.c')}"
        source_files.append(src)

    if not source_files:
        # No implementation files — header-only interface
        content = _render_interface_lib(dest)
    else:
        content = _render_static_lib(dest, source_files)

    (dest / "CMakeLists.txt").write_text(content, encoding="utf-8")


def _render_interface_lib(dest: Path) -> str:
    return """# AUTO-GENERATED by mockware
cmake_minimum_required(VERSION 3.16)

add_library(mock_sdk INTERFACE)
target_include_directories(mock_sdk INTERFACE
    ${CMAKE_CURRENT_LIST_DIR}/include
)
"""


def _render_static_lib(dest: Path, sources: list[str]) -> str:
    sources_text = "\n    ".join(sources)
    return f"""# AUTO-GENERATED by mockware
cmake_minimum_required(VERSION 3.16)

add_library(mock_sdk STATIC
    {sources_text}
)

target_include_directories(mock_sdk PUBLIC
    ${{CMAKE_CURRENT_LIST_DIR}}/include
)
"""
