from __future__ import annotations

from pathlib import Path


def generate_cmake(
    output_dir: str,
    data: dict,
    verbose: bool,
) -> None:
    """Generate a top-level CMakeLists.txt for the mock SDK tree."""
    dest = Path(output_dir)
    dest.mkdir(parents=True, exist_ok=True)

    functions = data.get("functions", {})
    source_files = _collect_source_paths(functions)

    if not source_files:
        content = _render_interface_lib()
    else:
        content = _render_static_lib(source_files)

    (dest / "CMakeLists.txt").write_text(content, encoding="utf-8")

    if verbose:
        print("  cmake: CMakeLists.txt")


def _collect_source_paths(functions: dict[str, dict]) -> list[str]:
    sources: set[str] = set()
    for fname, finfo in functions.items():
        if finfo.get("kind") == "inline":
            continue
        hdr = finfo.get("header")
        if hdr:
            src = f"source/{Path(hdr).with_suffix('.c')}"
        else:
            src = "source/general.c"
        sources.add(src)
    return sorted(sources)


def _render_interface_lib() -> str:
    return """# AUTO-GENERATED by mockware
cmake_minimum_required(VERSION 3.16)

add_library(mock_sdk INTERFACE)
target_include_directories(mock_sdk INTERFACE
    ${CMAKE_CURRENT_LIST_DIR}/include
)
"""


def _render_static_lib(sources: list[str]) -> str:
    sources_text = "\n    ".join(sources)
    return f"""# AUTO-GENERATED by mockware
cmake_minimum_required(VERSION 3.16)

add_library(mock_sdk STATIC
    {sources_text}
)

target_include_directories(mock_sdk PUBLIC
    ${{CMAKE_CURRENT_LIST_DIR}}/include
)
"""
