from __future__ import annotations

import re
from pathlib import Path

_STANDARD_TYPE_HEADERS: dict[str, str] = {
    "int8_t": "<stdint.h>",
    "int16_t": "<stdint.h>",
    "int32_t": "<stdint.h>",
    "int64_t": "<stdint.h>",
    "uint8_t": "<stdint.h>",
    "uint16_t": "<stdint.h>",
    "uint32_t": "<stdint.h>",
    "uint64_t": "<stdint.h>",
    "uintptr_t": "<stdint.h>",
    "intptr_t": "<stdint.h>",
    "size_t": "<stddef.h>",
    "ssize_t": "<sys/types.h>",
    "ptrdiff_t": "<stddef.h>",
    "wchar_t": "<stddef.h>",
    "bool": "<stdbool.h>",
    "_Bool": "<stdbool.h>",
    "FILE": "<stdio.h>",
    "va_list": "<stdarg.h>",
    "off_t": "<sys/types.h>",
    "time_t": "<time.h>",
    "clock_t": "<time.h>",
}


def needed_standard_includes(data: dict) -> set[str]:
    """Scan all YAML sections and return the set of required standard headers."""
    needed: set[str] = set()

    def _scan(value: str) -> None:
        for word in re.findall(r'\w+', value):
            hdr = _STANDARD_TYPE_HEADERS.get(word)
            if hdr:
                needed.add(hdr)

    for _, underlying in data.get("types", {}).items():
        _scan(str(underlying))

    for _, finfo in data.get("functions", {}).items():
        _scan(finfo.get("return", ""))
        for param in finfo.get("params", []):
            _scan(param)

    for _, mvalue in data.get("macros", {}).items():
        _scan(str(mvalue))

    for _, sinfo in data.get("structs", {}).items():
        sdef = sinfo.get("definition", sinfo) if isinstance(sinfo, dict) else sinfo
        _scan(str(sdef))

    for _, einfo in data.get("enums", {}).items():
        for vval in einfo.get("values", {}).values():
            _scan(str(vval))

    return needed


def generate_defs_headers(
    output_dir: str,
    data: dict,
    verbose: bool,
) -> None:
    """Generate ``mockware/{types,macros,enums,structs}.h`` in the include dir."""
    base = Path(output_dir) / "include" / "mockware"
    base.mkdir(parents=True, exist_ok=True)
    std_includes = needed_standard_includes(data)

    _write(base, "types.h", _render_types(data.get("types", {}), std_includes), verbose)
    _write(base, "macros.h", _render_macros(data.get("macros", {})), verbose)
    _write(base, "enums.h", _render_enums(data.get("enums", {})), verbose)
    _write(base, "structs.h", _render_structs(data.get("structs", {})), verbose)


def _write(base: Path, name: str, content: str, verbose: bool) -> None:
    (base / name).write_text(content, encoding="utf-8")
    if verbose:
        print(f"  defs: mockware/{name}")


def _render_types(types: dict[str, str],
                   std_includes: set[str] | None = None) -> str:
    lines = [
        "#pragma once",
        "// AUTO-GENERATED by mockware",
        "",
    ]
    if std_includes:
        for inc in sorted(std_includes):
            lines.append(f"#include {inc}")
        lines.append("")
    for tname, underlying in types.items():
        lines.append(f"typedef {underlying} {tname};")
    if types:
        lines.append("")
    return "\n".join(lines)


def _render_macros(macros: dict[str, str]) -> str:
    lines = [
        "#pragma once",
        "// AUTO-GENERATED by mockware",
        "",
    ]
    for name, value in macros.items():
        if isinstance(value, str) and value.startswith("("):
            lines.append(f"#define {name}{value}")
        else:
            lines.append(f"#define {name} {value}")
    if macros:
        lines.append("")
    return "\n".join(lines)


def _render_enums(enums: dict[str, dict]) -> str:
    lines = [
        "#pragma once",
        "// AUTO-GENERATED by mockware",
        "",
    ]
    for ename, einfo in enums.items():
        lines.append("typedef enum {")
        for vname, vval in einfo.get("values", {}).items():
            lines.append(f"    {vname} = {vval},")
        lines.append(f"}} {ename};")
        lines.append("")
    if not enums:
        lines.append("/* no enums */")
        lines.append("")
    return "\n".join(lines)


def _render_structs(structs: dict[str, dict]) -> str:
    lines = [
        "#pragma once",
        "// AUTO-GENERATED by mockware",
        "",
    ]
    for sname, sinfo in structs.items():
        if isinstance(sinfo, str):
            definition = sinfo
        else:
            definition = sinfo.get("definition", "")
        if definition:
            for dline in definition.split("\n"):
                lines.append(dline)
            lines.append("")
    if not structs:
        lines.append("/* no structs */")
        lines.append("")
    return "\n".join(lines)
