from __future__ import annotations

from pathlib import Path

from ..models import Config
from .util import params_str


def generate_fakes_header(output_dir: str, config: Config, verbose: bool = False) -> None:
    dest = Path(output_dir) / "include" / "mockware" / "fakes.h"
    dest.parent.mkdir(parents=True, exist_ok=True)

    lines: list[str] = [
        "#pragma once",
        "// AUTO-GENERATED by mockware -- do not edit manually",
        "",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
    ]

    # Include every header that has functions or namespaces with functions
    # so that types used in function pointer signatures are defined.
    included_headers: set[str] = set()
    for hdr_path_str, header in sorted(config.headers.items()):
        has_functions = bool(header.functions) or _namespace_has_functions(header.namespaces)
        if has_functions:
            included_headers.add(hdr_path_str)
            lines.append(f'#include "{hdr_path_str}"')

    if included_headers:
        lines.append("")

    has_c_mocks = any(
        header.functions or _namespace_has_functions(header.namespaces)
        for _, header in config.headers.items()
    )

    if has_c_mocks:
        lines.append("#ifdef __cplusplus")
        lines.append('extern "C" {')
        lines.append("#endif")
        lines.append("")

    for hdr_path_str, header in sorted(config.headers.items()):
        for fname, func in sorted(header.functions.items()):
            ret = func.return_type
            ps = params_str(func.params)
            lines.append(f"extern {ret} (*{fname}_mock)({ps});")

        for ns_name, ns in sorted(header.namespaces.items()):
            for fname, func in sorted(ns.functions.items()):
                ret = func.return_type
                ps = params_str(func.params)
                lines.append(f"extern {ret} (*{fname}_mock)({ps});")

    if has_c_mocks:
        lines.append("")
        lines.append("#ifdef __cplusplus")
        lines.append("}")
        lines.append("#endif")
        lines.append("")
        dest.write_text("\n".join(lines) + "\n", encoding="utf-8")
        if verbose:
            print("  fakes: mockware/fakes.h")
    else:
        if verbose:
            print("  fakes: (skipped -- no function mocks)")


def _namespace_has_functions(namespaces: dict) -> bool:
    for ns in namespaces.values():
        if ns.functions:
            return True
    return False
