from __future__ import annotations

from pathlib import Path


def generate_fakes_headers(
    output_dir: str,
    known_apis: dict[str, dict],
    used_headers: set[str],
    verbose: bool,
) -> None:
    """Generate per-component ``<component>_fakes.h`` headers with extern
    declarations for every overridable function pointer.

    Each file wraps declarations in ``extern "C"`` for C++ compatibility.
    """
    # Group headers by component
    comp_groups: dict[str, list[tuple[str, str, dict]]] = {}
    for hdr in sorted(used_headers):
        entry = known_apis.get(hdr)
        if not entry:
            continue
        comp = _component_name(hdr)
        funcs = _collect_functions(entry)
        if not funcs:
            continue
        comp_groups.setdefault(comp, []).append((hdr, comp, funcs))

    for comp, groups in comp_groups.items():
        content = _render_fakes_header(comp, groups)
        dest = Path(output_dir) / "include" / f"{comp}_fakes.h"
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(content, encoding="utf-8")
        if verbose:
            print(f"  fakes: {comp}_fakes.h")


# Known ESP-IDF component header collisions — headers whose stem differs
# from their component name are mapped here.
# Key: header stem (without .h)   → Value: component name
_COMPONENT_ALIASES: dict[str, str] = {
    "esp_wifi_types": "esp_wifi",
    "esp_wifi_default": "esp_wifi",
    "esp_wifi_sta": "esp_wifi",
    "esp_netif_types": "esp_netif",
    "esp_netif_default": "esp_netif",
    "esp_timer_priv": "esp_timer",
    "esp_timer_internal": "esp_timer",
    "esp_event_base": "esp_event",
    "esp_http_client_priv": "esp_http_client",
    "esp_mqtt_client_priv": "esp_mqtt_client",
    "esp_websocket_client_priv": "esp_websocket_client",
    "soc_caps": "soc",
    "soc_include": "soc",
}


def _component_name(header_path: str) -> str:
    """Derive a component name from a header path.

    Rules (first match wins):
      - ``"driver/gpio.h"``       → first path segment  → ``"driver"``
      - ``"freertos/FreeRTOS.h"`` → first path segment  → ``"freertos"``
      - ``"esp_wifi_types.h"``    → alias lookup        → ``"esp_wifi"``
      - ``"esp_wifi.h"``          → stem                → ``"esp_wifi"``
      - ``"extra.h"``             → stem                → ``"extra"``
    """
    if "/" in header_path:
        return header_path.split("/")[0]

    stem = Path(header_path).stem
    return _COMPONENT_ALIASES.get(stem, stem)


def _collect_functions(entry: dict) -> list[dict]:
    """Return list of function metadata for all non-inline functions."""
    funcs: list[dict] = []
    for fname, finfo in entry.get("functions", {}).items():
        if finfo.get("kind") == "inline":
            continue
        ret = finfo.get("return", "void")
        params_list = finfo.get("params", [])
        params_str = ", ".join(params_list) if params_list else "void"
        funcs.append({
            "name": fname,
            "return": ret,
            "params": params_str,
            "header": entry,  # keep for source comment
        })
    return funcs


def _render_fakes_header(comp: str, groups: list[tuple[str, str, list[dict]]]) -> str:
    lines: list[str] = [
        "// AUTO-GENERATED by mockware",
        f"// Mock fakes for component: {comp}",
        "// Include this in test files instead of writing extern declarations.",
        "#pragma once",
        "",
        "#ifdef __cplusplus",
        'extern "C" {',
        "#endif",
        "",
    ]

    for hdr, _comp, funcs in groups:
        lines.append(f"/* ── {hdr} ── */")
        for f in funcs:
            decl = f"extern {f['return']} (*{f['name']}_fp)({f['params']});"
            lines.append(decl)
        lines.append("")

    lines.extend([
        "#ifdef __cplusplus",
        "} /* extern \"C\" */",
        "#endif",
        "",
    ])

    return "\n".join(lines)
