from __future__ import annotations

from pathlib import Path


def generate_fakes_header(
    output_dir: str,
    data: dict,
    verbose: bool,
) -> None:
    """Generate a single ``include/mockware/fakes.h``.

    Contains ``extern`` declarations for every function pointer,
    wrapped in ``extern "C"`` for C++ compatibility.
    Includes the defs headers so types are visible.
    """
    functions = data.get("functions", {})
    funcs = _collect_functions(functions)
    if not funcs:
        return

    base = Path(output_dir) / "include" / "mockware"
    base.mkdir(parents=True, exist_ok=True)

    content = _render_fakes_header(funcs)
    (base / "fakes.h").write_text(content, encoding="utf-8")

    if verbose:
        print("  defs: mockware/fakes.h")


def _collect_functions(functions: dict[str, dict]) -> list[dict]:
    result: list[dict] = []
    for fname, finfo in functions.items():
        if finfo.get("kind") == "inline":
            continue
        ret = finfo.get("return", "void")
        params_list = finfo.get("params", [])
        params_str = ", ".join(params_list) if params_list else "void"
        result.append({
            "name": fname,
            "return": ret,
            "params": params_str,
        })
    return result


def _render_fakes_header(funcs: list[dict]) -> str:
    lines = [
        "// AUTO-GENERATED by mockware",
        "// Overridable function-pointer declarations for unit testing.",
        "#pragma once",
        "",
        '#include "mockware/types.h"',
        '#include "mockware/macros.h"',
        '#include "mockware/enums.h"',
        '#include "mockware/structs.h"',
        "",
        "#ifdef __cplusplus",
        'extern "C" {',
        "#endif",
        "",
    ]
    for f in funcs:
        decl = f"extern {f['return']} (*{f['name']}_mock)({f['params']});"
        lines.append(decl)

    if funcs:
        lines.append("")

    lines.extend([
        "#ifdef __cplusplus",
        '} /* extern "C" */',
        "#endif",
        "",
    ])
    return "\n".join(lines)
