from __future__ import annotations

from pathlib import Path

from ..models import ClassDef, Config, Header
from .util import auto_body, params_str, split_member_var


def generate_headers(output_dir: str, config: Config, verbose: bool = False) -> None:
    for hdr_path_str, header in sorted(config.headers.items()):
        if header.language == "cpp":
            content = _render_cpp_header(hdr_path_str, header)
        else:
            content = _render_c_header(hdr_path_str, header)
        dest = Path(output_dir) / "include" / hdr_path_str
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(content, encoding="utf-8")
        if verbose:
            print(f"  header: {hdr_path_str}")


def _header_preamble(hdr_path: str) -> list[str]:
    return [
        "#pragma once",
        "// AUTO-GENERATED by mockware -- do not edit manually",
        f"// Source: {hdr_path}",
        "",
    ]


def _render_includes(header: Header) -> list[str]:
    lines: list[str] = []
    for inc in header.includes:
        if inc.startswith("<") and inc.endswith(">"):
            lines.append(f"#include {inc}")
        else:
            lines.append(f'#include "{inc}"')
    for inc in header.system_includes:
        if inc.startswith("<"):
            lines.append(f"#include {inc}")
        else:
            lines.append(f"#include <{inc}>")
    if header.includes or header.system_includes:
        lines.append("")
    return lines


def _render_macros(header: Header) -> list[str]:
    lines: list[str] = []
    for name, macro in sorted(header.macros.items()):
        if macro.value is not None:
            lines.append(f"#define {name} {macro.value}")
        elif macro.kind == "variadic" and macro.body:
            lines.append(f"#define {name}(...) {macro.body}")
        elif macro.body:
            lines.append(f"#define {name}{macro.body}")
        else:
            lines.append(f"#define {name}")
    if header.macros:
        lines.append("")
    return lines


def _render_types(header: Header) -> list[str]:
    lines: list[str] = []
    for name, td in sorted(header.types.items()):
        if td.definition:
            lines.append(td.definition)
        elif td.underlying:
            lines.append(f"typedef {td.underlying} {name};")
    if header.types:
        lines.append("")
    return lines


def _render_enums(enums: dict, indent: str = "") -> list[str]:
    lines: list[str] = []
    for name, enum_val in sorted(enums.items()):
        if enum_val.values:
            lines.append(f"{indent}typedef enum {{")
            for val_name, val in enum_val.values.items():
                lines.append(f"{indent}    {val_name} = {val},")
            lines.append(f"{indent}}} {name};")
    if enums:
        lines.append("")
    return lines


def _render_c_header(hdr_path: str, header: Header) -> str:
    lines: list[str] = _header_preamble(hdr_path)
    lines.extend(_render_includes(header))
    lines.extend(_render_macros(header))
    lines.extend(_render_enums(header.enums))
    lines.extend(_render_types(header))
    if header.functions:
        lines.append("#ifdef __cplusplus")
        lines.append('extern "C" {')
        lines.append("#endif")
        lines.append("")
        for fname, func in sorted(header.functions.items()):
            lines.append(f"{func.return_type} {fname}({params_str(func.params)});")
        lines.append("")
        lines.append("#ifdef __cplusplus")
        lines.append("}")
        lines.append("#endif")
        lines.append("")
    return "\n".join(lines) + "\n"


def _render_cpp_header(hdr_path: str, header: Header) -> str:
    lines: list[str] = _header_preamble(hdr_path)
    lines.extend(_render_includes(header))
    lines.extend(_render_macros(header))
    lines.extend(_render_enums(header.enums))
    lines.extend(_render_types(header))

    for ns_name, ns in sorted(header.namespaces.items()):
        lines.append(f"namespace {ns_name} {{")
        lines.append("")
        lines.extend(_render_enums(ns.enums, indent="    "))

        for cls_name, cls in sorted(ns.classes.items()):
            lines.extend(_render_cpp_class(cls_name, cls, indent="    "))

        for fname, func in sorted(ns.functions.items()):
            lines.append(f"    {func.return_type} {fname}({params_str(func.params)});")
        if ns.functions:
            lines.append("")

        lines.append(f"}}  // namespace {ns_name}")
        lines.append("")

    return "\n".join(lines) + "\n"


def _render_cpp_class(cls_name: str, cls: ClassDef, indent: str = "") -> str:
    lines: list[str] = [f"{indent}class {cls_name} {{", f"{indent}public:"]

    for ctor in cls.constructors:
        ctor_params = params_str(ctor.params)
        init_entries = list(ctor.init_list) if ctor.init_list else _auto_init_list(
            cls.member_variables, ctor.params
        )
        init_str = " : " + ", ".join(init_entries) if init_entries else ""
        if ctor.body:
            lines.append(f"{indent}    {cls_name}({ctor_params}){init_str} {{ {ctor.body} }}")
        else:
            lines.append(f"{indent}    {cls_name}({ctor_params}){init_str} {{}}")

    if cls.destructor is not None:
        if cls.destructor == "":
            lines.append(f"{indent}    virtual ~{cls_name}() = default;")
        else:
            lines.append(f"{indent}    virtual ~{cls_name}() {{ {cls.destructor} }}")
    else:
        lines.append(f"{indent}    virtual ~{cls_name}() = default;")

    for mname, method in sorted(cls.methods.items()):
        const_str = " const" if method.is_const else ""
        ret = method.return_type
        ps = params_str(method.params)
        if method.body is not None:
            lines.append(f"{indent}    virtual {ret} {mname}({ps}){const_str} {{ {method.body} }}")
        else:
            default_body = auto_body(ret)
            if default_body:
                lines.append(f"{indent}    virtual {ret} {mname}({ps}){const_str} {{ {default_body} }}")
            else:
                lines.append(f"{indent}    virtual {ret} {mname}({ps}){const_str} {{}}")

    for mname, method in sorted(cls.static_methods.items()):
        ret = method.return_type
        ps = params_str(method.params)
        if method.body is not None:
            lines.append(f"{indent}    static {ret} {mname}({ps}) {{ {method.body} }}")
        else:
            default_body = auto_body(ret)
            if default_body:
                lines.append(f"{indent}    static {ret} {mname}({ps}) {{ {default_body} }}")
            else:
                lines.append(f"{indent}    static {ret} {mname}({ps}) {{}}")

    if cls.member_variables:
        lines.append("")
        lines.append(f"{indent}protected:")
        for var_name, var_type_str in sorted(cls.member_variables.items()):
            clean_type, _ = split_member_var(var_type_str)
            lines.append(f"{indent}    {clean_type} {var_name};")

    lines.append(f"{indent}}};")
    lines.append("")
    return lines


def _auto_init_list(
    member_vars: dict[str, str], ctor_params: list[str]
) -> list[str]:
    init_list: list[str] = []
    ctor_param_names = set()
    for p in ctor_params:
        parts = p.rsplit(None, 1)
        if len(parts) == 2:
            candidate = parts[1].lstrip("*").rstrip("[]")
            if candidate:
                ctor_param_names.add(candidate)
    for var_name, var_type_str in member_vars.items():
        if var_name in ctor_param_names:
            init_list.append(f"{var_name}({var_name})")
        else:
            _, default = split_member_var(var_type_str)
            if default is not None:
                init_list.append(f"{var_name}({default})")
    return init_list
