from __future__ import annotations

from pathlib import Path

from ..models import Config
from .util import arg_names, auto_body, params_str


def generate_sources(output_dir: str, config: Config, verbose: bool = False) -> None:
    for hdr_path_str, header in sorted(config.headers.items()):
        if not header.functions and not _namespace_has_functions(header.namespaces):
            continue
        if header.language == "cpp":
            content = _render_cpp_source(hdr_path_str, header)
        else:
            content = _render_c_source(hdr_path_str, header)
        suffix = ".cpp" if header.language == "cpp" else ".c"
        source_path = Path(hdr_path_str).with_suffix(suffix)
        dest = Path(output_dir) / "source" / source_path
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(content, encoding="utf-8")
        if verbose:
            print(f"  source: {source_path}")


def _namespace_has_functions(namespaces: dict) -> bool:
    for ns in namespaces.values():
        if ns.functions:
            return True
    return False


def _render_c_source(hdr_path: str, header) -> str:
    lines: list[str] = [
        "// AUTO-GENERATED by mockware -- do not edit manually",
        f'// Source: {hdr_path}',
        "",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        f'#include "{hdr_path}"',
        '#include "mockware/fakes.h"',
        "",
    ]
    for fname, func in sorted(header.functions.items()):
        lines.extend(_render_function_stub(fname, func))
    return "\n".join(lines) + "\n"


def _render_function_stub(fname: str, func) -> list[str]:
    ret = func.return_type
    ps = params_str(func.params)
    anames = arg_names(func.params)
    anames_str = ", ".join(anames)
    body = func.body if func.body is not None else auto_body(ret)

    lines: list[str] = [
        f"static {ret} {fname}_default({ps}) {{",
    ]
    if body:
        lines.append(f"    {body}")
    lines.append("}")
    lines.append(f"{ret} (*{fname}_mock)({ps}) = {fname}_default;")
    lines.append("")
    lines.append(f"{ret} {fname}({ps}) {{")
    if ret == "void":
        lines.append(f"    {fname}_mock({anames_str});")
    else:
        lines.append(f"    return {fname}_mock({anames_str});")
    lines.append("}")
    lines.append("")
    return lines


def _render_cpp_source(hdr_path: str, header) -> str:
    lines: list[str] = [
        "// AUTO-GENERATED by mockware -- do not edit manually",
        f'// Source: {hdr_path}',
        "",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
        f'#include "{hdr_path}"',
        '#include "mockware/fakes.h"',
        "",
    ]
    for ns_name, ns in sorted(header.namespaces.items()):
        for fname, func in sorted(ns.functions.items()):
            lines.extend(_render_function_stub(fname, func))
    return "\n".join(lines) + "\n"
