from __future__ import annotations

from pathlib import Path

_DEFAULT_BODIES: dict[str, str] = {
    "void": "",
    "esp_err_t": "return ESP_OK;",
    "bool": "return false;",
    "int": "return 0;",
    "int32_t": "return 0;",
    "uint32_t": "return 0;",
    "int64_t": "return 0;",
    "uint64_t": "return 0;",
    "size_t": "return 0;",
    "ssize_t": "return 0;",
    "char": "return '\\0';",
    "float": "return 0.0f;",
    "double": "return 0.0;",
    "BaseType_t": "return 0;",
}


def generate_implementations(
    output_dir: str,
    known_apis: dict[str, dict],
    used_headers: set[str],
    verbose: bool,
) -> None:
    """Generate .c implementation files with default stubs + function pointers.

    Produces one .c per header in a ``source/`` mirror of the include tree.
    """
    for hdr_path_str in sorted(used_headers):
        entry = known_apis.get(hdr_path_str)
        if not entry:
            continue

        functions = entry.get("functions", {})
        # Skip headers that only have data types, no functions
        if not functions:
            continue

        content = _render_impl(hdr_path_str, entry)
        dest = Path(output_dir) / "source" / hdr_path_str
        dest = dest.with_suffix(".c")
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(content, encoding="utf-8")

        if verbose:
            print(f"  impl: {hdr_path_str}")


def _render_impl(hdr_path: str, entry: dict) -> str:
    lines: list[str] = [
        "// AUTO-GENERATED by mockware — do not edit manually",
        f'// Source: {hdr_path}',
        "",
        f'#include "{hdr_path}"',
        "",
    ]

    functions = entry.get("functions", {})

    for fname, finfo in functions.items():
        # Skip inline functions — they're expanded in the header
        if finfo.get("kind") == "inline":
            continue

        ret = finfo.get("return", "void")
        params_list = finfo.get("params", [])
        params_str = ", ".join(params_list) if params_list else "void"

        # Default implementation name
        default_name = f"{fname}_default"

        # Generate the default function with the body from YAML or auto
        body = finfo.get("body")
        if body:
            default_body = body
        else:
            default_body = _auto_body(ret)

        # Printf-style stub bodies for better debugging
        if not body and ret != "void":
            default_body = default_body  # use auto-generated

        lines.append(f"static {ret} {default_name}({params_str}) {{")
        if default_body:
            lines.append(f"    {default_body}")
        lines.append("}")
        lines.append("")

        # Function pointer declaration
        lines.append(f"{ret} (*{fname}_fp)({params_str}) = {default_name};")
        lines.append("")

        # Actual function — forwards to the function pointer
        lines.append(f"{ret} {fname}({params_str}) {{")
        if ret == "void":
            lines.append(f"    {fname}_fp({_arg_names(params_list)});")
        else:
            lines.append(f"    return {fname}_fp({_arg_names(params_list)});")
        lines.append("}")
        lines.append("")

    return "\n".join(lines) + "\n"


def _auto_body(return_type: str) -> str:
    """Auto-generate a default return statement based on return type string."""
    # Direct lookup
    body = _DEFAULT_BODIES.get(return_type)
    if body is not None:
        return body

    # Pointer types
    if return_type.endswith("*"):
        return "return NULL;"

    # Struct types
    if return_type.startswith("struct "):
        return f"return ({return_type}){{0}};"

    # Enum types
    if return_type.startswith("enum "):
        return "return 0;"

    # Typedefs — many are integer-like
    return "return 0;"


def _arg_names(params_list: list[str]) -> str:
    """Extract just the argument names from ``type name`` param strings."""
    names: list[str] = []
    for p in params_list:
        parts = p.rsplit(None, 1)
        if len(parts) == 2:
            names.append(parts[1])
        else:
            names.append(p)
    return ", ".join(names)
