from __future__ import annotations

from pathlib import Path


def generate_headers(
    output_dir: str,
    known_apis: dict[str, dict],
    used_headers: set[str],
    verbose: bool,
) -> None:
    """Generate stub header files for every header in *known_apis* that is
    used by the project (or is a transitive dependency of one).
    """
    # Expand used headers to include transitive dependencies
    needed = expand_includes(known_apis, used_headers)

    for hdr_path_str in sorted(needed):
        entry = known_apis.get(hdr_path_str)
        if not entry:
            continue

        content = _render_header(hdr_path_str, entry, known_apis)
        dest = Path(output_dir) / "include" / hdr_path_str
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(content, encoding="utf-8")

        if verbose:
            print(f"  header: {hdr_path_str}")


def expand_includes(
    known_apis: dict[str, dict],
    used: set[str],
) -> set[str]:
    """Breadth-first expansion of include dependencies."""
    result = set(used)
    queue = list(used)
    while queue:
        hdr = queue.pop(0)
        entry = known_apis.get(hdr)
        if not entry:
            continue
        for dep in entry.get("includes", []):
            if dep not in result:
                if dep in known_apis:
                    result.add(dep)
                    queue.append(dep)
                # else: dep is not in our knowledge base → warn at call site
    return result


def _render_header(
    hdr_path: str,
    entry: dict,
    known_apis: dict[str, dict],
) -> str:
    lines: list[str] = [
        "#pragma once",
        "// AUTO-GENERATED by mockware — do not edit manually",
        f'// Source: {hdr_path}',
        "",
    ]

    # Includes
    for inc in entry.get("includes", []):
        # Determine if it's a system or local include
        if "/" in inc:
            lines.append(f'#include "{inc}"')
        else:
            lines.append(f'#include "{inc}"')

    if entry.get("includes"):
        lines.append("")

    # Macros — object-like first, then function-like
    for name, value in entry.get("macros", {}).items():
        if isinstance(value, dict) and value.get("kind") == "function-like":
            params = ", ".join(value.get("params", []))
            body = value.get("body", "")
            if value.get("variadic"):
                lines.append(f"#define {name}({params}, ...) {body}")
            else:
                lines.append(f"#define {name}({params}) {body}")
        else:
            lines.append(f"#define {name} {value}")

    if entry.get("macros"):
        lines.append("")

    # Types (typedefs)
    for type_name, underlying in entry.get("types", {}).items():
        lines.append(f"typedef {underlying} {type_name};")

    if entry.get("types"):
        lines.append("")

    # Enums
    for enum_name, einfo in entry.get("enums", {}).items():
        values = einfo.get("values", {})
        lines.append("typedef enum {")
        for vname, vval in values.items():
            if isinstance(vval, str) and vval.startswith("/*"):
                lines.append(f"    {vname}")
            else:
                lines.append(f"    {vname} = {vval},")
        lines.append(f"}} {enum_name};")
        lines.append("")

    # Structs (raw definition)
    for sname, sinfo in entry.get("structs", {}).items():
        definition = sinfo.get("definition")
        if definition:
            for dline in definition.split("\n"):
                lines.append(dline)
            lines.append("")

    # Functions
    for fname, finfo in entry.get("functions", {}).items():
        ret = finfo.get("return", "void")
        params_list = finfo.get("params", [])
        params_str = ", ".join(params_list) if params_list else "void"

        if finfo.get("kind") == "inline":
            # Emit the full inline definition (body is stored in YAML)
            body = finfo.get("body", "")
            if body:
                for bline in body.split("\n"):
                    lines.append(bline)
                lines.append("")
            else:
                lines.append(f"static inline {ret} {fname}({params_str});")
        else:
            lines.append(f"{ret} {fname}({params_str});")

    if entry.get("functions"):
        lines.append("")

    return "\n".join(lines) + "\n"
