from __future__ import annotations

from pathlib import Path

_DEFAULT_BODIES: dict[str, str] = {
    "void": "",
    "bool": "return false;",
    "int": "return 0;",
    "int32_t": "return 0;",
    "uint32_t": "return 0;",
    "int64_t": "return 0;",
    "uint64_t": "return 0;",
    "size_t": "return 0;",
    "ssize_t": "return 0;",
    "char": "return '\\0';",
    "float": "return 0.0f;",
    "double": "return 0.0;",
}

_GENERAL_C = "general.c"


def generate_implementations(
    output_dir: str,
    data: dict,
    verbose: bool,
) -> None:
    """Generate .c implementation files.

    Functions with a ``header`` tag → ``source/<header>.c``.
    Functions without a ``header`` tag → ``source/general.c``.
    """
    functions = data.get("functions", {})
    source_dir = Path(output_dir) / "source"
    source_dir.mkdir(parents=True, exist_ok=True)

    # Group functions by output file
    per_file: dict[str, dict[str, dict]] = {}
    for fname, finfo in functions.items():
        if finfo.get("kind") == "inline":
            continue
        hdr = finfo.get("header")
        out_file = hdr if hdr else _GENERAL_C
        if out_file not in per_file:
            per_file[out_file] = {}
        per_file[out_file][fname] = finfo

    for out_file, funcs in sorted(per_file.items()):
        if out_file == _GENERAL_C:
            content = _render_general_impl(funcs)
        else:
            content = _render_per_header_impl(out_file, funcs)

        dest = source_dir / out_file
        if out_file != _GENERAL_C:
            dest = dest.with_suffix(".c")
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(content, encoding="utf-8")

        if verbose:
            print(f"  impl: {out_file if out_file != _GENERAL_C else 'general'}")


def _render_per_header_impl(hdr_path: str, funcs: dict[str, dict]) -> str:
    lines = [
        "// AUTO-GENERATED by mockware — do not edit manually",
        f'// Source: {hdr_path}',
        "",
        f'#include "{hdr_path}"',
        "",
    ]
    for fname, finfo in funcs.items():
        lines.extend(_render_function(fname, finfo))
    return "\n".join(lines) + "\n"


def _render_general_impl(funcs: dict[str, dict]) -> str:
    lines = [
        "// AUTO-GENERATED by mockware — do not edit manually",
        '// Source: general',
        "",
        '#include "mockware/types.h"',
        '#include "mockware/macros.h"',
        '#include "mockware/enums.h"',
        '#include "mockware/structs.h"',
        "",
    ]
    for fname, finfo in funcs.items():
        lines.extend(_render_function(fname, finfo))
    return "\n".join(lines) + "\n"


def _render_function(fname: str, finfo: dict) -> list[str]:
    ret = finfo.get("return", "void")
    params_list = finfo.get("params", [])
    params_str = ", ".join(params_list) if params_list else "void"
    default_name = f"{fname}_default"
    body = finfo.get("body") or _auto_body(ret)

    lines = [
        f"static {ret} {default_name}({params_str}) {{",
    ]
    if body:
        lines.append(f"    {body}")
    lines.append("}")
    lines.append("")
    lines.append(f"{ret} (*{fname}_mock)({params_str}) = {default_name};")
    lines.append("")
    lines.append(f"{ret} {fname}({params_str}) {{")
    if ret == "void":
        lines.append(f"    {fname}_mock({_arg_names(params_list)});")
    else:
        lines.append(f"    return {fname}_mock({_arg_names(params_list)});")
    lines.append("}")
    lines.append("")
    return lines


def _auto_body(return_type: str) -> str:
    body = _DEFAULT_BODIES.get(return_type)
    if body is not None:
        return body
    if return_type.endswith("*"):
        return "return NULL;"
    if return_type.startswith("struct "):
        return f"return ({return_type}){{0}};"
    if return_type.startswith("enum "):
        return "return 0;"
    return "return 0;"


def _arg_names(params_list: list[str]) -> str:
    names: list[str] = []
    for p in params_list:
        parts = p.rsplit(None, 1)
        if len(parts) == 2:
            names.append(parts[1])
        else:
            names.append(p)
    return ", ".join(names)
