from __future__ import annotations

from pathlib import Path

_DEFS_INCLUDES = [
    '#include "mockware/types.h"',
    '#include "mockware/macros.h"',
    '#include "mockware/enums.h"',
    '#include "mockware/structs.h"',
]


def generate_headers(
    output_dir: str,
    data: dict,
    used_headers: set[str],
    verbose: bool,
) -> None:
    """Generate stub header files.

    Each stub includes the shared definition headers (types, macros,
    enums, structs) plus function declarations tagged to that header.
    """
    needed = expand_includes(data.get("headers", {}), used_headers)
    functions = data.get("functions", {})
    headers = data.get("headers", {})

    for hdr_path_str in sorted(needed):
        entry = headers.get(hdr_path_str)
        if entry is None:
            entry = {"includes": []}

        funcs = _header_functions(hdr_path_str, functions)
        content = _render_header(hdr_path_str, entry, funcs)
        dest = Path(output_dir) / "include" / hdr_path_str
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(content, encoding="utf-8")

        if verbose:
            print(f"  header: {hdr_path_str}")


def expand_includes(
    headers: dict[str, dict],
    used: set[str],
) -> set[str]:
    """Breadth-first expansion of include dependencies."""
    result = set(used)
    queue = list(used)
    while queue:
        hdr = queue.pop(0)
        entry = headers.get(hdr)
        if not entry:
            continue
        for dep in entry.get("includes", []):
            if dep not in result:
                if dep in headers:
                    result.add(dep)
                    queue.append(dep)
    return result


def _header_functions(
    hdr_path: str,
    functions: dict[str, dict],
) -> dict[str, dict]:
    return {
        fname: finfo
        for fname, finfo in functions.items()
        if finfo.get("header") == hdr_path
    }


def _render_header(
    hdr_path: str,
    entry: dict,
    funcs: dict[str, dict],
) -> str:
    lines = [
        "#pragma once",
        "// AUTO-GENERATED by mockware — do not edit manually",
        f'// Source: {hdr_path}',
        "",
    ]

    for inc in entry.get("includes", []):
        lines.append(f'#include "{inc}"')

    if entry.get("includes"):
        lines.append("")

    lines.extend(_DEFS_INCLUDES)
    lines.append("")

    for fname, finfo in funcs.items():
        ret = finfo.get("return", "void")
        params_list = finfo.get("params", [])
        params_str = ", ".join(params_list) if params_list else "void"

        if finfo.get("kind") == "inline":
            body = finfo.get("body", "")
            if body:
                for bline in body.split("\n"):
                    lines.append(bline)
                lines.append("")
            else:
                lines.append(f"static inline {ret} {fname}({params_str});")
        else:
            lines.append(f"{ret} {fname}({params_str});")

    if funcs:
        lines.append("")

    return "\n".join(lines) + "\n"
