import tempfile
from pathlib import Path

from mockware.generator.cmake_gen import generate_cmake

DATA_WITH_FUNCS: dict = {
    "headers": {"esp_err.h": {"includes": []}},
    "types": {},
    "macros": {},
    "enums": {},
    "structs": {},
    "functions": {
        "esp_err_to_name": {"return": "int", "params": [],
                            "header": "esp_err.h"},
    },
}

DATA_HEADER_ONLY: dict = {
    "headers": {"esp_err.h": {"includes": []}},
    "types": {},
    "macros": {},
    "enums": {},
    "structs": {},
    "functions": {},
}

DATA_INLINE_ONLY: dict = {
    "headers": {"foo.h": {"includes": []}},
    "types": {},
    "macros": {},
    "enums": {},
    "structs": {},
    "functions": {
        "bar": {"kind": "inline", "return": "void", "params": [],
                "body": "", "header": "foo.h"},
    },
}


def test_generates_static_lib_with_sources() -> None:
    with tempfile.TemporaryDirectory() as tmp:
        out = Path(tmp) / "mock-sdk"
        generate_cmake(str(out), DATA_WITH_FUNCS, verbose=False)

        cmake = (out / "CMakeLists.txt").read_text()
        assert "AUTO-GENERATED by mockware" in cmake
        assert "add_library(mock_sdk STATIC" in cmake
        assert "source/esp_err.c" in cmake


def test_generates_interface_lib_without_functions() -> None:
    with tempfile.TemporaryDirectory() as tmp:
        out = Path(tmp) / "mock-sdk"
        generate_cmake(str(out), DATA_HEADER_ONLY, verbose=False)

        cmake = (out / "CMakeLists.txt").read_text()
        assert "add_library(mock_sdk INTERFACE" in cmake


def test_skipped_for_inline_only_headers() -> None:
    with tempfile.TemporaryDirectory() as tmp:
        out = Path(tmp) / "mock-sdk"
        generate_cmake(str(out), DATA_INLINE_ONLY, verbose=False)

        cmake = (out / "CMakeLists.txt").read_text()
        assert "add_library(mock_sdk INTERFACE" in cmake
