import tempfile
from pathlib import Path

from mockware.generator.stub_header_gen import expand_includes, generate_headers
from mockware.generator.stub_impl_gen import generate_implementations

SAMPLE_DATA: dict = {
    "headers": {
        "esp_err.h": {
            "includes": [],
        },
        "esp_wifi.h": {
            "includes": ["esp_err.h"],
        },
    },
    "types": {"esp_err_t": "int"},
    "macros": {"ESP_OK": "0", "ESP_FAIL": "-1"},
    "enums": {
        "wifi_mode_t": {
            "values": {"WIFI_MODE_NULL": 0, "WIFI_MODE_STA": 1}
        }
    },
    "structs": {},
    "functions": {
        "esp_wifi_start": {"return": "esp_err_t", "params": [],
                           "header": "esp_wifi.h"},
        "esp_wifi_stop": {"return": "esp_err_t", "params": [],
                          "header": "esp_wifi.h"},
        "esp_err_to_name": {"return": "const char*",
                            "params": ["esp_err_t err"],
                            "header": "esp_err.h"},
    },
}


def test_generates_headers() -> None:
    with tempfile.TemporaryDirectory() as tmp:
        out = Path(tmp) / "mock-sdk"
        used = {"esp_wifi.h", "esp_err.h"}
        generate_headers(str(out), SAMPLE_DATA, used, verbose=False)

        assert (out / "include" / "esp_err.h").exists()
        assert (out / "include" / "esp_wifi.h").exists()

        hdr = (out / "include" / "esp_wifi.h").read_text()
        assert "#pragma once" in hdr
        assert "AUTO-GENERATED by mockware" in hdr
        assert 'typedef enum' not in hdr  # enums now in mockware/enums.h
        assert '#include "mockware/enums.h"' in hdr
        assert "esp_err_t esp_wifi_start(void);" in hdr


def test_generates_implementations() -> None:
    with tempfile.TemporaryDirectory() as tmp:
        out = Path(tmp) / "mock-sdk"
        generate_implementations(str(out), SAMPLE_DATA, verbose=False)

        assert (out / "source" / "esp_wifi.c").exists()
        assert (out / "source" / "esp_err.c").exists()

        impl = (out / "source" / "esp_wifi.c").read_text()
        assert "AUTO-GENERATED by mockware" in impl
        assert "esp_err_t (*esp_wifi_start_mock)(void) = esp_wifi_start_default;" in impl
        assert "return esp_wifi_start_mock();" in impl
        assert "return 0;" in impl


def test_expand_includes_includes_transitive_deps() -> None:
    needed = expand_includes(SAMPLE_DATA["headers"], {"esp_wifi.h"})
    assert "esp_wifi.h" in needed
    assert "esp_err.h" in needed
    assert len(needed) == 2


def test_generated_header_has_correct_include_chain() -> None:
    with tempfile.TemporaryDirectory() as tmp:
        out = Path(tmp) / "mock-sdk"
        used = {"esp_wifi.h", "esp_err.h"}
        generate_headers(str(out), SAMPLE_DATA, used, verbose=False)

        hdr = (out / "include" / "esp_wifi.h").read_text()
        assert '#include "esp_err.h"' in hdr
        assert '#include "mockware/types.h"' in hdr
        assert '#include "mockware/macros.h"' in hdr


def test_expand_includes_ignores_missing_deps() -> None:
    headers = {
        "a.h": {"includes": ["b.h"]},
    }
    needed = expand_includes(headers, {"a.h"})
    assert needed == {"a.h"}


def test_general_c_for_untagged_functions() -> None:
    data = {
        "headers": {},
        "types": {},
        "macros": {},
        "enums": {},
        "structs": {},
        "functions": {
            "orphan_func": {"return": "int", "params": []},
        },
    }
    with tempfile.TemporaryDirectory() as tmp:
        out = Path(tmp) / "mock-sdk"
        generate_implementations(str(out), data, verbose=False)
        assert (out / "source" / "general.c").exists()
        content = (out / "source" / "general.c").read_text()
        assert "orphan_func" in content
