import tempfile
from pathlib import Path

from mockware.generator.cmake_gen import generate_cmake


SAMPLE_APIS = {
    "esp_err.h": {
        "includes": [], "macros": {}, "types": {},
        "enums": {}, "structs": {},
        "functions": {"esp_err_to_name": {"return": "int", "params": []}},
    },
}

SAMPLE_APIS_HEADER_ONLY = {
    "esp_err.h": {
        "includes": [], "macros": {}, "types": {},
        "enums": {}, "structs": {},
        "functions": {},
    },
}


def test_generates_static_lib_with_sources() -> None:
    with tempfile.TemporaryDirectory() as tmp:
        out = Path(tmp) / "mock-sdk"
        generate_cmake(str(out), SAMPLE_APIS, {"esp_err.h"})

        cmake = (out / "CMakeLists.txt").read_text()
        assert "AUTO-GENERATED by mockware" in cmake
        assert "add_library(mock_sdk STATIC" in cmake
        assert "source/esp_err.c" in cmake
        assert "include" in cmake


def test_generates_interface_lib_without_functions() -> None:
    with tempfile.TemporaryDirectory() as tmp:
        out = Path(tmp) / "mock-sdk"
        generate_cmake(str(out), SAMPLE_APIS_HEADER_ONLY, {"esp_err.h"})

        cmake = (out / "CMakeLists.txt").read_text()
        assert "add_library(mock_sdk INTERFACE" in cmake
        assert "source" not in cmake


def test_skipped_for_inline_only_headers() -> None:
    apis_inline = {
        "foo.h": {
            "includes": [], "macros": {}, "types": {},
            "enums": {}, "structs": {},
            "functions": {
                "bar": {"kind": "inline", "return": "void", "params": [], "body": ""}
            },
        },
    }
    with tempfile.TemporaryDirectory() as tmp:
        out = Path(tmp) / "mock-sdk"
        generate_cmake(str(out), apis_inline, {"foo.h"})
        cmake = (out / "CMakeLists.txt").read_text()
        assert "add_library(mock_sdk INTERFACE" in cmake
