import tempfile
from pathlib import Path

from mockware.generator.stub_header_gen import generate_headers, expand_includes
from mockware.generator.stub_impl_gen import generate_implementations
from mockware.generator.yaml_reader import read_yaml


SAMPLE_DATA: dict[str, dict] = {
    "esp_err.h": {
        "includes": [],
        "macros": {"ESP_OK": "0", "ESP_FAIL": "-1"},
        "types": {"esp_err_t": "int"},
        "enums": {},
        "structs": {},
        "functions": {
            "esp_err_to_name": {
                "return": "const char*",
                "params": ["esp_err_t err"],
            }
        },
    },
    "esp_wifi.h": {
        "includes": ["esp_err.h"],
        "macros": {"WIFI_MODE_STA": "0"},
        "enums": {
            "wifi_mode_t": {
                "values": {"WIFI_MODE_NULL": 0, "WIFI_MODE_STA": 1}
            }
        },
        "types": {},
        "structs": {},
        "functions": {
            "esp_wifi_start": {"return": "esp_err_t", "params": []},
            "esp_wifi_stop": {"return": "esp_err_t", "params": []},
        },
    },
}


def test_generates_headers() -> None:
    with tempfile.TemporaryDirectory() as tmp:
        out = Path(tmp) / "mock-sdk"
        used = {"esp_wifi.h", "esp_err.h"}
        generate_headers(str(out), SAMPLE_DATA, used, verbose=False)

        assert (out / "include" / "esp_err.h").exists()
        assert (out / "include" / "esp_wifi.h").exists()

        hdr = (out / "include" / "esp_wifi.h").read_text()
        assert "#pragma once" in hdr
        assert "AUTO-GENERATED by mockware" in hdr
        assert 'typedef enum' in hdr
        assert "WIFI_MODE_STA = 1" in hdr
        assert "esp_err_t esp_wifi_start(void);" in hdr


def test_generates_implementations() -> None:
    with tempfile.TemporaryDirectory() as tmp:
        out = Path(tmp) / "mock-sdk"
        used = {"esp_wifi.h", "esp_err.h"}
        generate_implementations(str(out), SAMPLE_DATA, used, verbose=False)

        assert (out / "source" / "esp_wifi.c").exists()
        assert (out / "source" / "esp_err.c").exists()

        impl = (out / "source" / "esp_wifi.c").read_text()
        assert "AUTO-GENERATED by mockware" in impl
        assert "esp_err_t (*esp_wifi_start_fp)(void) = esp_wifi_start_default;" in impl
        assert "return esp_wifi_start_fp();" in impl
        assert "return ESP_OK;" in impl


def test_expand_includes_includes_transitive_deps() -> None:
    needed = expand_includes(SAMPLE_DATA, {"esp_wifi.h"})
    assert "esp_wifi.h" in needed
    assert "esp_err.h" in needed
    assert len(needed) == 2


def test_generated_header_has_correct_include_chain() -> None:
    with tempfile.TemporaryDirectory() as tmp:
        out = Path(tmp) / "mock-sdk"
        used = {"esp_wifi.h", "esp_err.h"}
        generate_headers(str(out), SAMPLE_DATA, used, verbose=False)

        hdr = (out / "include" / "esp_wifi.h").read_text()
        # Should include its dependency
        assert '#include "esp_err.h"' in hdr


def test_expand_includes_ignores_missing_deps() -> None:
    apis = {
        "a.h": {"includes": ["b.h"], "macros": {}, "types": {},
                "enums": {}, "structs": {}, "functions": {}}
    }
    needed = expand_includes(apis, {"a.h"})
    assert needed == {"a.h"}  # b.h is not in the API dict
